// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOBy3chI6rCGpHMoBCZKFRO4wPWm3n07I',
    appId: '1:139311884130:web:c2f22f5bb5914c44b3ee3b',
    messagingSenderId: '139311884130',
    projectId: 'multidev-cookingbook',
    authDomain: 'multidev-cookingbook.firebaseapp.com',
    storageBucket: 'multidev-cookingbook.appspot.com',
    measurementId: 'G-WE0532PT92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlP5JsBpnwJVV-VT2zVrV-jBI4_SHyvog',
    appId: '1:139311884130:android:095025768319ab80b3ee3b',
    messagingSenderId: '139311884130',
    projectId: 'multidev-cookingbook',
    storageBucket: 'multidev-cookingbook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjv2M9FKcA_oWTcdStg77tZ7TtzR7fjXs',
    appId: '1:139311884130:ios:a82041c1ff4357d0b3ee3b',
    messagingSenderId: '139311884130',
    projectId: 'multidev-cookingbook',
    storageBucket: 'multidev-cookingbook.appspot.com',
    androidClientId: '139311884130-8lghbfneiim8hf2o1njea2ii1j5tkrhf.apps.googleusercontent.com',
    iosClientId: '139311884130-or4s4am5mgof35llpdvmuhbm8evdp4g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookingbookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjv2M9FKcA_oWTcdStg77tZ7TtzR7fjXs',
    appId: '1:139311884130:ios:a82041c1ff4357d0b3ee3b',
    messagingSenderId: '139311884130',
    projectId: 'multidev-cookingbook',
    storageBucket: 'multidev-cookingbook.appspot.com',
    androidClientId: '139311884130-8lghbfneiim8hf2o1njea2ii1j5tkrhf.apps.googleusercontent.com',
    iosClientId: '139311884130-or4s4am5mgof35llpdvmuhbm8evdp4g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookingbookApp',
  );
}
